/**
 * data/line-questions/*.json を読み込み、subject × grade ごとの
 * 重複排除済 topic リストを `src/data/generated/line-topics.generated.ts` に出力する。
 *
 * 使い方:
 *   npx tsx scripts/generate-line-topics.ts
 *
 * 問題を新しく登録した後（manage-line-questions.ts で追加した後）に再実行する。
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');
const QUESTIONS_DIR = join(REPO_ROOT, 'data', 'line-questions');
const OUTPUT_PATH = join(
  REPO_ROOT,
  'src',
  'data',
  'generated',
  'line-topics.generated.ts'
);

interface QuestionRow {
  subject: string;
  grade: string;
  topic: string;
}

const GRADE_LABEL_TO_NUMBER: Record<string, 1 | 2 | 3> = {
  中1: 1,
  中2: 2,
  中3: 3,
};

function main() {
  const files = readdirSync(QUESTIONS_DIR).filter((f) => f.endsWith('.json'));
  if (files.length === 0) {
    console.warn(`[generate-line-topics] no JSON files in ${QUESTIONS_DIR}`);
    return;
  }

  const map: Record<string, Record<number, Set<string>>> = {};

  for (const file of files) {
    const path = join(QUESTIONS_DIR, file);
    const raw = readFileSync(path, 'utf-8');
    const rows = JSON.parse(raw) as QuestionRow[];
    for (const r of rows) {
      const subject = r.subject;
      const gradeNum = GRADE_LABEL_TO_NUMBER[r.grade];
      const topic = r.topic;
      if (!subject || !gradeNum || !topic) continue;
      map[subject] ??= {};
      map[subject][gradeNum] ??= new Set();
      map[subject][gradeNum].add(topic);
    }
  }

  const subjects = Object.keys(map).sort();
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/generate-line-topics.ts');
  lines.push('// Do not edit manually. Run: npx tsx scripts/generate-line-topics.ts');
  lines.push('');
  lines.push('export type LineSubject = ' + subjects.map((s) => `'${s}'`).join(' | ') + ';');
  lines.push('export type LineGrade = 1 | 2 | 3;');
  lines.push('');
  lines.push('export const lineQuestionTopics: Record<LineSubject, Record<LineGrade, string[]>> = {');
  for (const s of subjects) {
    lines.push(`  ${s}: {`);
    for (const g of [1, 2, 3] as const) {
      const topics = map[s]?.[g] ? Array.from(map[s][g]).sort() : [];
      const items = topics.map((t) => JSON.stringify(t)).join(', ');
      lines.push(`    ${g}: [${items}],`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`[generate-line-topics] wrote ${OUTPUT_PATH}`);

  for (const s of subjects) {
    for (const g of [1, 2, 3] as const) {
      const count = map[s]?.[g]?.size ?? 0;
      console.log(`  ${s} grade${g}: ${count} topics`);
    }
  }
}

main();
