/**
 * data/content/history/ を学年別に読み、LIFF「じっくり学ぶ」用の
 * 学習データを TS モジュールにバンドルする。
 *
 * 使い方:
 *   npx tsx scripts/generate-line-study-content.ts
 *
 * 出力（学年別、Lazy-load 可能）:
 *   src/data/generated/line-study-history-g1.generated.ts
 *   src/data/generated/line-study-history-g2.generated.ts
 *
 * 学年マップ（data/content/history/<folder> ベース）:
 *   grade1: 01-history-basics / 02-ancient-world / 03-japanese-origins /
 *           04-ancient-state / 05-warrior-kamakura / 06-medieval-world
 *   grade2: 07-early-modern / 08-edo-establishment / 09-modern-era /
 *           10-bakumatsu / 11-meiji-early / 12-meiji-late
 *
 * 各 topic は flashcards / quiz.questions のみを保持（videos, chatId は
 * LIFF で使わないため除外しサイズ削減）。
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');
const SRC_DIR = join(REPO_ROOT, 'data', 'content', 'history');
const OUT_DIR = join(REPO_ROOT, 'src', 'data', 'generated');

const GRADE_FOLDERS: Record<number, string[]> = {
  1: [
    '01-history-basics',
    '02-ancient-world',
    '03-japanese-origins',
    '04-ancient-state',
    '05-warrior-kamakura',
    '06-medieval-world',
  ],
  2: [
    '07-early-modern',
    '08-edo-establishment',
    '09-modern-era',
    '10-bakumatsu',
    '11-meiji-early',
    '12-meiji-late',
  ],
};

const ERA_DISPLAY_NAMES: Record<string, { name: string; icon: string; period: string }> = {
  // grade 1
  'history-basics': { name: '歴史の基礎', icon: '📜', period: '時代の区分・年代の表し方' },
  'ancient-world': { name: '古代文明の世界', icon: '🏛️', period: '700万年前〜7世紀' },
  'japanese-origins': { name: '日本の成り立ち', icon: '🏠', period: '1万年前〜6世紀' },
  'ancient-state': { name: '古代国家の形成', icon: '🏯', period: '6世紀〜12世紀' },
  'warrior-kamakura': { name: '武士の世の中', icon: '⚔️', period: '11世紀〜14世紀' },
  'medieval-world': { name: '中世の世界と室町時代', icon: '🗡️', period: '13世紀〜16世紀' },
  // grade 2
  'early-modern': { name: '近世の幕開け', icon: '🌍', period: '15世紀〜16世紀' },
  'edo-establishment': { name: '江戸幕府の成立', icon: '🏯', period: '17世紀' },
  'modern-era': { name: '近代革命と国家形成', icon: '🌍', period: '17世紀〜19世紀' },
  bakumatsu: { name: '幕末', icon: '⚔️', period: '1853年〜1868年' },
  'meiji-early': { name: '明治時代（前期）', icon: '🌅', period: '1868年〜1889年' },
  'meiji-late': { name: '明治時代（後期）', icon: '🏭', period: '1889年〜1912年' },
};

interface RawFlashcard {
  id: string;
  front: string;
  back: string;
  explanation?: string;
  difficulty?: string;
}

interface RawQuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
  difficulty?: string;
}

interface RawTopic {
  subjectId: string;
  eraId: string;
  topicId: string;
  name: string;
  subtitle?: string;
  icon?: string;
  order?: number;
  flashcards?: RawFlashcard[];
  quiz?: { questions?: RawQuizQuestion[] };
}

interface OutTopic {
  topicId: string;
  name: string;
  subtitle: string;
  icon: string;
  order: number;
  flashcards: RawFlashcard[];
  quiz: RawQuizQuestion[];
}

interface OutEra {
  eraId: string;
  eraName: string;
  eraIcon: string;
  eraPeriod: string;
  topics: OutTopic[];
}

function loadTopicsFromFolder(folder: string): { eraId: string; topics: OutTopic[] } {
  const dir = join(SRC_DIR, folder);
  const files = readdirSync(dir).filter((f) => f.endsWith('.json'));
  if (files.length === 0) return { eraId: folder, topics: [] };
  const topics: OutTopic[] = [];
  let eraId = folder;
  for (const file of files) {
    const raw = readFileSync(join(dir, file), 'utf-8');
    const data = JSON.parse(raw) as RawTopic;
    eraId = data.eraId;
    topics.push({
      topicId: data.topicId,
      name: data.name,
      subtitle: data.subtitle ?? '',
      icon: data.icon ?? '',
      order: data.order ?? 0,
      flashcards: data.flashcards ?? [],
      quiz: data.quiz?.questions ?? [],
    });
  }
  topics.sort((a, b) => a.order - b.order);
  return { eraId, topics };
}

function emitGrade(grade: number, folders: string[]) {
  const eras: OutEra[] = [];
  for (const folder of folders) {
    const { eraId, topics } = loadTopicsFromFolder(folder);
    if (topics.length === 0) continue;
    const meta = ERA_DISPLAY_NAMES[eraId] ?? {
      name: eraId,
      icon: '📚',
      period: '',
    };
    eras.push({
      eraId,
      eraName: meta.name,
      eraIcon: meta.icon,
      eraPeriod: meta.period,
      topics,
    });
  }

  const banner =
    '// AUTO-GENERATED by scripts/generate-line-study-content.ts\n' +
    `// Grade ${grade} – history\n` +
    '// Do not edit manually. Re-run on data/content/history/ updates.\n' +
    '// Run: npx tsx scripts/generate-line-study-content.ts\n\n';

  // 型を grade1 ファイルにだけ出して、他は import するのが本来きれいだが、
  // 単純化のため各ファイルに同じ型を埋め込む（自己完結 / lazy chunk 化しやすい）。
  const types = `export interface StudyFlashcard {
  id: string;
  front: string;
  back: string;
  explanation?: string;
  difficulty?: string;
}

export interface StudyQuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
  difficulty?: string;
}

export interface StudyTopic {
  topicId: string;
  name: string;
  subtitle: string;
  icon: string;
  order: number;
  flashcards: StudyFlashcard[];
  quiz: StudyQuizQuestion[];
}

export interface StudyEra {
  eraId: string;
  eraName: string;
  eraIcon: string;
  eraPeriod: string;
  topics: StudyTopic[];
}

`;

  const body = `export const lineStudyHistoryEras: StudyEra[] = ${JSON.stringify(eras, null, 2)};\n`;

  const out = join(OUT_DIR, `line-study-history-g${grade}.generated.ts`);
  writeFileSync(out, banner + types + body, 'utf-8');

  let totalTopics = 0;
  let totalFC = 0;
  let totalQuiz = 0;
  console.log(`\n[grade ${grade}] -> ${out}`);
  for (const era of eras) {
    console.log(`  ${era.eraId} (${era.eraName}): ${era.topics.length} topics`);
    for (const t of era.topics) {
      totalTopics++;
      totalFC += t.flashcards.length;
      totalQuiz += t.quiz.length;
    }
  }
  console.log(
    `  → eras=${eras.length} topics=${totalTopics} flashcards=${totalFC} quizQ=${totalQuiz}`
  );
}

function main() {
  for (const [grade, folders] of Object.entries(GRADE_FOLDERS)) {
    emitGrade(Number(grade), folders);
  }
}

main();
