/**
 * 公式LINE 出題用「問題IDインデックス」を Firestore `questions` から生成するスクリプト。
 *
 * 目的（Firestore read 削減）:
 *   selectAndSendQuestion（毎日配信 / 追加で解く / 復帰 / 初回1問目の共通出題経路）は
 *   従来「出題のたびに subject×grade の questions を全件 .get()（1回 約200〜400 read）」
 *   していた。出題は 1 日 3,000 回超のため、これが read 課金（"App Engine" SKU）の主因だった。
 *
 *   本スクリプトは subject×grade ごとの { id, topic } の一覧を生成物として吐き出す。
 *   ランタイムはこのインデックスでメモリ上で候補（topic 絞り込み・最近出題の除外）を作り、
 *   選んだ 1 件だけ `questions/{id}` を doc().get() する。これで 1 出題 約300 read → 約1 read。
 *
 * source of truth:
 *   ライブの Firestore `questions` collection そのもの（content / legacy の混在を問わず実データに
 *   完全一致させるため、content JSON ではなく Firestore を読む）。よって本スクリプトは
 *   sync-questions-from-content.ts の「後」に実行する（同期済みの状態を index 化する）。
 *
 * 出力:
 *   functions/src/generated/line-question-index.generated.ts
 *
 * 実行:
 *   gcloud auth application-default login   # 初回のみ（ADC）
 *   npx tsx scripts/generate-line-question-index.ts
 *
 * ⚠️ 単元/問題を追加・編集したら sync-questions の後にこれも再実行すること。
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FIREBASE_PROJECT_ID = 'chatstudy-63477';

const VALID_GRADES = ['中1', '中2', '中3'] as const;
const VALID_SUBJECTS = [
  'history',
  'english',
  'science',
  'math',
  'geography',
] as const;
type ValidGrade = (typeof VALID_GRADES)[number];
type ValidSubject = (typeof VALID_SUBJECTS)[number];

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');
const OUT_PATH = join(
  REPO_ROOT,
  'functions',
  'src',
  'generated',
  'line-question-index.generated.ts'
);

async function main(): Promise<void> {
  const { initializeApp, applicationDefault, getApps } = await import(
    'firebase-admin/app'
  );
  const { getFirestore } = await import('firebase-admin/firestore');
  if (getApps().length === 0) {
    initializeApp({
      credential: applicationDefault(),
      projectId: FIREBASE_PROJECT_ID,
    });
  }
  const db = getFirestore();

  // questions 全件を 1 回だけ read（subject/grade/topic のみ転送）。これはデプロイ時の
  // 1 回限りのスキャンで、ランタイムの per-request read を恒久的に削減するためのもの。
  const snap = await db
    .collection('questions')
    .select('subject', 'grade', 'topic')
    .get();

  console.log(`[gen-question-index] 読み込んだ questions: ${snap.size} 件`);

  // key = `${subject}-${grade}` → Array<[id, topic]>
  const index: Record<string, Array<[string, string]>> = {};
  let skipped = 0;
  const skippedReasons: Record<string, number> = {};

  for (const doc of snap.docs) {
    const subject = doc.get('subject');
    const grade = doc.get('grade');
    const topic = doc.get('topic');
    if (
      typeof subject !== 'string' ||
      !VALID_SUBJECTS.includes(subject as ValidSubject)
    ) {
      skipped++;
      skippedReasons[`subject:${String(subject)}`] =
        (skippedReasons[`subject:${String(subject)}`] ?? 0) + 1;
      continue;
    }
    if (
      typeof grade !== 'string' ||
      !VALID_GRADES.includes(grade as ValidGrade)
    ) {
      skipped++;
      skippedReasons[`grade:${String(grade)}`] =
        (skippedReasons[`grade:${String(grade)}`] ?? 0) + 1;
      continue;
    }
    const topicStr = typeof topic === 'string' ? topic : '';
    const key = `${subject}-${grade}`;
    (index[key] ??= []).push([doc.id, topicStr]);
  }

  // 安定した出力（diff ノイズ削減）のため key と id でソート。
  const sortedKeys = Object.keys(index).sort();
  for (const key of sortedKeys) {
    index[key].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  }

  console.log('[gen-question-index] subject×grade 別の件数:');
  for (const key of sortedKeys) {
    console.log(`  ${key}: ${index[key].length} 問`);
  }
  if (skipped > 0) {
    console.warn(
      `[gen-question-index] スキップ ${skipped} 件（subject/grade 不正）:`,
      skippedReasons
    );
  }

  const banner =
    '// AUTO-GENERATED by scripts/generate-line-question-index.ts — DO NOT EDIT.\n' +
    '// 出題候補の [id, topic] を subject×grade 単位でまとめた ID インデックス。\n' +
    '// selectAndSendQuestion はこれでメモリ上で候補を絞り、選んだ 1 件だけ Firestore から読む。\n' +
    '// 単元/問題を追加・編集したら sync-questions の後にこのスクリプトを再実行すること。\n\n';

  const types =
    '/** [問題ドキュメントID, topic 名] */\n' +
    'export type QuestionIndexEntry = readonly [id: string, topic: string];\n\n';

  const lines: string[] = [];
  lines.push(
    'export const QUESTION_INDEX: Record<string, readonly QuestionIndexEntry[]> = {'
  );
  for (const key of sortedKeys) {
    lines.push(`  ${JSON.stringify(key)}: [`);
    for (const [id, topic] of index[key]) {
      lines.push(`    [${JSON.stringify(id)}, ${JSON.stringify(topic)}],`);
    }
    lines.push('  ],');
  }
  lines.push('};\n');

  writeFileSync(OUT_PATH, banner + types + lines.join('\n'), 'utf-8');
  console.log(`[gen-question-index] 出力: ${OUT_PATH}`);
}

main().catch((e) => {
  console.error('[gen-question-index] 失敗:', e);
  process.exit(1);
});
