/**
 * data/content/history/01〜04 を読み、LIFF「じっくり学ぶ」用の
 * 学習データを TS モジュールにバンドルする。
 *
 * 使い方:
 *   npx tsx scripts/generate-line-study-content.ts
 *
 * 出力: src/data/generated/line-study-history-g1.generated.ts
 *
 * 含めるエラ（grade1 = 01-04）:
 *   01-history-basics
 *   02-ancient-world
 *   03-japanese-origins
 *   04-ancient-state
 *
 * 各 topic は flashcards / quiz.questions のみを保持（videos, chatId は
 * LIFF では使わないため除外しサイズ削減）。
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');
const SRC_DIR = join(REPO_ROOT, 'data', 'content', 'history');
const OUT_PATH = join(
  REPO_ROOT,
  'src',
  'data',
  'generated',
  'line-study-history-g1.generated.ts'
);

const ERA_FOLDERS = [
  '01-history-basics',
  '02-ancient-world',
  '03-japanese-origins',
  '04-ancient-state',
];

const ERA_DISPLAY_NAMES: Record<string, { name: string; icon: string; period: string }> = {
  'history-basics': { name: '歴史の基礎', icon: '📜', period: '時代の区分・年代の表し方' },
  'ancient-world': { name: '古代文明の世界', icon: '🏛️', period: '700万年前〜7世紀' },
  'japanese-origins': { name: '日本の成り立ち', icon: '🏠', period: '1万年前〜6世紀' },
  'ancient-state': { name: '古代国家の形成', icon: '🏯', period: '6世紀〜12世紀' },
};

interface RawFlashcard {
  id: string;
  front: string;
  back: string;
  explanation?: string;
  difficulty?: string;
}

interface RawQuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
  difficulty?: string;
}

interface RawTopic {
  subjectId: string;
  eraId: string;
  topicId: string;
  name: string;
  subtitle?: string;
  icon?: string;
  order?: number;
  flashcards?: RawFlashcard[];
  quiz?: { questions?: RawQuizQuestion[] };
}

interface OutTopic {
  topicId: string;
  name: string;
  subtitle: string;
  icon: string;
  order: number;
  flashcards: RawFlashcard[];
  quiz: RawQuizQuestion[];
}

interface OutEra {
  eraId: string;
  eraName: string;
  eraIcon: string;
  eraPeriod: string;
  topics: OutTopic[];
}

function loadTopicsFromFolder(folder: string): OutTopic[] {
  const dir = join(SRC_DIR, folder);
  const files = readdirSync(dir).filter((f) => f.endsWith('.json'));
  const topics: OutTopic[] = [];
  for (const file of files) {
    const raw = readFileSync(join(dir, file), 'utf-8');
    const data = JSON.parse(raw) as RawTopic;
    topics.push({
      topicId: data.topicId,
      name: data.name,
      subtitle: data.subtitle ?? '',
      icon: data.icon ?? '',
      order: data.order ?? 0,
      flashcards: data.flashcards ?? [],
      quiz: data.quiz?.questions ?? [],
    });
  }
  return topics.sort((a, b) => a.order - b.order);
}

function main() {
  const eras: OutEra[] = [];
  for (const folder of ERA_FOLDERS) {
    const topics = loadTopicsFromFolder(folder);
    if (topics.length === 0) continue;
    const eraId = topics[0]
      ? (() => {
          // 各 topic は同じ eraId を持つ
          const raw = JSON.parse(
            readFileSync(
              join(SRC_DIR, folder, readdirSync(join(SRC_DIR, folder))[0]),
              'utf-8'
            )
          ) as RawTopic;
          return raw.eraId;
        })()
      : folder;
    const meta = ERA_DISPLAY_NAMES[eraId] ?? {
      name: eraId,
      icon: '📚',
      period: '',
    };
    eras.push({
      eraId,
      eraName: meta.name,
      eraIcon: meta.icon,
      eraPeriod: meta.period,
      topics,
    });
  }

  const banner =
    '// AUTO-GENERATED by scripts/generate-line-study-content.ts\n' +
    '// Do not edit manually. Re-run on data/content/history/ updates.\n' +
    '// Run: npx tsx scripts/generate-line-study-content.ts\n\n';

  const types = `export interface StudyFlashcard {
  id: string;
  front: string;
  back: string;
  explanation?: string;
  difficulty?: string;
}

export interface StudyQuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
  difficulty?: string;
}

export interface StudyTopic {
  topicId: string;
  name: string;
  subtitle: string;
  icon: string;
  order: number;
  flashcards: StudyFlashcard[];
  quiz: StudyQuizQuestion[];
}

export interface StudyEra {
  eraId: string;
  eraName: string;
  eraIcon: string;
  eraPeriod: string;
  topics: StudyTopic[];
}

`;

  const body = `export const lineStudyHistoryG1: StudyEra[] = ${JSON.stringify(eras, null, 2)};\n`;

  writeFileSync(OUT_PATH, banner + types + body, 'utf-8');

  let totalTopics = 0;
  let totalFC = 0;
  let totalQuiz = 0;
  for (const era of eras) {
    console.log(`  ${era.eraId} (${era.eraName}): ${era.topics.length} topics`);
    for (const t of era.topics) {
      totalTopics++;
      totalFC += t.flashcards.length;
      totalQuiz += t.quiz.length;
    }
  }
  console.log(
    `\n[generate-line-study-content] wrote ${OUT_PATH}\n  eras: ${eras.length}, topics: ${totalTopics}, flashcards: ${totalFC}, quiz Q: ${totalQuiz}`
  );
}

main();
